ex 12

diff --git a/.github/workflows/deployment_pipeline.yml b/.github/workflows/deployment_pipeline.yml
--- a/.github/workflows/deployment_pipeline.yml
+++ b/.github/workflows/deployment_pipeline.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  simple_deployment_pipeline:
+  lint_build_test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -24,7 +24,7 @@ jobs:
 
   playwright_tests:
     runs-on: ubuntu-latest
-    needs: simple_deployment_pipeline
+    needs: lint_build_test
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
@@ -50,6 +50,20 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: superfly/flyctl-actions/setup-flyctl@master
-      - run: flyctl deploy --remote-only
+      - name: Deploy to Fly.io
+        run: flyctl deploy --remote-only
+        env:
+          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
+      - name: Check deployment health
+        run: |
+          echo "Wait 20secs"
+          sleep 20
+          if ! curl -f https://fso-11-ancient-pond-4440.fly.dev/health; then
+            echo "Health check failed"
+            flyctl releases rollback --yes
+            exit 1
+          else
+            echo "Health check passed"
+          fi
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
